# Generated by Django 4.1.5 on 2023-11-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
