# Generated by Django 4.1.5 on 2023-11-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_services', '0002_alter_answer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
